### ISSUE TITLE
Little image related bugs

### ISSUE THREAD

**Issue by SteveBarnett** [universalcore/unicore-cms-gem#11]
- 404 on http://tz.gem.unicore.io/static/img/logo_x2.png. Remove reference, or add 2x logo.
- http://tz.gem.unicore.io/static/img/base.jpg seems a bit big. (640x238) Resize down to 320?
- Looks like images could be optimised a bit more. Just from images on home page:

> Steves-MacBook-Pro➜  grunt : master ✘ :✖✹✭ ᐅ  grunt imagemin
> Running "imagemin:dynamic" (imagemin) task
> ✔ img/_resp/base.jpg (saved 1.87 kB)
> ✔ img/_resp/banner.jpg (already optimized)
> ✔ img/_resp/girl_declaration.png (saved 43 B)
> ✔ img/_resp/what_is_girl_effect.png (saved 959 B)
> ✔ img/_resp/logo.png (saved 864 B)
> Minified 5 images (saved 3.74 kB)

**Comment by smn** [comment]
👋  @SteveBarnett, hope you're doing well :)

**Comment by SteveBarnett** [comment]
@smn 👋 :)
