### ISSUE TITLE
Flatpage content can be returned from search

### ISSUE THREAD

**Issue by nathanbegbie** [universalcore/unicore-cms-gem#20]
![girl_effect_mobile___universal_core](https://cloud.githubusercontent.com/assets/7100966/6227584/7c3c3430-b6aa-11e4-95ba-e558e2995897.png)
Flatpage stuff (Contact, Terms & Conditions, Tips on Use) is stored as Pages in CMS. This means that elasticsearch indexes it. So it's returned in search results.

**Comment by nathanbegbie** [comment]
![girl_effect_mobile___universal_core](https://cloud.githubusercontent.com/assets/7100966/6227697/b9cb50dc-b6ab-11e4-8657-390b8c005791.png)

**Comment by miltontony** [comment]
@nathanbegbie good point, but why not? maybe the T's and C's have something important that you're looking for?

**Comment by smn** [comment]
The only issue is that the links in the search results are assuming you're going to a page that's in a category. Flatpages don't have categories and so the rendering & experience can break because the search results have no means of determining if a page is a flat page or not.

**Comment by nathanbegbie** [comment]
@miltontony also, the language filter is failing for flatpage stuff

**Comment by SteveBarnett** [comment]
Would it be possible to do these things (maybe as new tickets)?
- Group results by category
- Display results as a `ul` under the category name
- display the full page title and ditch `Read more >` (I think long titles were only a problem on FFL?)
- Add some `margin` between the pagination and the results

**Comment by miltontony** [comment]
2 next steps I propose:
- make the detail pages not fail if primary_category is not specified. An if block should suffice to remove the breadcrum that's usually the culprit
- add a failing test for the flat page language filtering and see where it's going wrong

**Comment by SteveBarnett** [comment]
Including the static pages in the search result is fine, as long as they are clearly visually marked as "different stuff." Hence the grouping by category.

**Comment by nathanbegbie** [comment]
Trying to work out scope of what I'm doing though. @SteveBarnett Elasticsearch orders results by importance, so grouping by categories overrides that. Also, its complicated by the fact that we've paginated, so you could go a while before getting a category that you want. @miltontony are there other sites that do this?

**Comment by miltontony** [comment]
@SteveBarnett @nathanbegbie I'm `-1` on grouping by category. Perhaps just a label of sorts to identify the categories would be enough. Alsi, this is MVP so I think the simpler the better. We can revist the layout at a later stage.

**Comment by smn** [comment]
yeah, I'm with @miltontony. If we label the result with the name of the category it is in we'd add some more context (at the expense of using some screen real estate). If there's no category we should assume it's a flat page and render it as such.

@nathanbegbie & @SteveBarnett would this be acceptable?

**Comment by nathanbegbie** [comment]
@miltontony MVP - Most Valuable Product ? So then I'm going to sort out these problems in the branch I'm currently working on. With regards to adding a test to see about language filtering, do I need to add `search_results.py` to `unicorecmsgem>tests`, copy/paste from `unicore-cms` and add more tests?

**Comment by miltontony** [comment]
@nathanbegbie `Minimum Viable Product` With regards to tests, you can add them directly to `unicore-cms` in a feature branch. That would avoid duplicating the tests

**Comment by nathanbegbie** [comment]
@miltontony I misinterpreted those results with different languages. The language filter is not failing for flatpage stuff, I just needed to upgrade to unicore-cms 1.6.1. Apologies. Also, I am going to adjust the filter for search in unicore-cms, to filter out all results with no primary category, rather than messing about with the templates, to avoid issues with pagination. Can I close this issue and create another in unicore-cms?

**Comment by miltontony** [comment]
`-1` on filtering out static content. Since you're already updating templates, I think adding that condition on the `primary_category` should be straightforward

**Comment by SteveBarnett** [comment]
I agree: static content needs to stay in.

Given the above discussion, I propose we have the full title as a link, showing the category it's in, linked to that category. Like so.

> [Are you in a bad crowd?](link/to/article) in [Life Tips](link/to/lifetips)
> [Alone and suffering](link/to/article) in [Girl Heroes](link/to/girlheroes)
